apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          # Add liveness probe
          livenessProbe:
            httpGet:
              path: /var/www/html/index.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          # # Add readiness probe
          readinessProbe:
            httpGet:
              path: /var/www/html/index.php
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
          # Add startup probe
          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 30
            periodSeconds: 10
