apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-01
  template:
    metadata:
      labels:
        app: nginx-01
    spec:
      containers:
        - name: nginx-01
          image: nginx
          ports:
            - containerPort: 80
          # Add liveness probe
          livenessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          # # Add readiness probe
          readinessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
          # Add startup probe
          startupProbe:
            httpGet:
              path: /index.html
              port: 80
            failureThreshold: 30
            periodSeconds: 10
